### ISSUE TITLE
Which version of Panta is supported by Pasa?

### ISSUE THREAD

**Issue by gongyh** [amromics/pasa#1]
The output file format of the latest Panta has changed. Which Panta commit is supported by Pasa?

**Comment by vanhoan310** [comment]
Thank you for your interest in running our software. I have put a backup version of Pasa-compatible Panta here:
https://github.com/vanhoan310/Pasa_Panta

Here is the instruction to run Pasa: https://github.com/amromics/pasa/blob/main/Reproducibility/runPasaPipeline.py

A sample reference data can be found here: https://drive.google.com/file/d/1KUc6PWOxQxiW0M3fnp6MoUcjuoLL49Hj/view?usp=sharing

Please let me know if you have any question.

**Comment by gongyh** [comment]
Thanks! It works now.
